# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86b4c5cc3d59234862b360802b37380af4907e6920e0a0e6f04952fefab4acd6f00eee79feace550bbb6b35dd6a35856f421268ea23b5e0f08ccb464232bcbab

test:
  secret_key_base: 6d4934e7b9a5ad35c42b32797b29baafe331907a61f418a785a7ae84965d33f0be8e72fe6bfc057bbb5d605a44bbea848ec7f1e9519225b5c8db25ea93f71df0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
